### ISSUE TITLE
Unable to enter commands in console on both Chome and Edge

### ISSUE THREAD

**Issue by noahbowman** [pcottle/learnGitBranching#1026] opened 2022-10-10 20:24 UTC
Using Windows 10 - I can interact with the UI but the console does not take any input on both Chrome and Edge.

![image](https://user-images.githubusercontent.com/34799961/194946132-20cbb8da-d25f-41e3-ac77-7152f92869d2.png)

However, when I use Firefox I can enter commands just fine

![image](https://user-images.githubusercontent.com/34799961/194946241-c6c93420-74dc-4789-a9e8-a454b07701e2.png)

The cursor is also visible in Firefox on the console, but is not visible on the other two browsers.

Firefox:
![image](https://user-images.githubusercontent.com/34799961/194946575-42953a33-c5e3-43cd-ba92-5cbea1022341.png)

Other:
![image](https://user-images.githubusercontent.com/34799961/194946341-c9bfd8a3-51d7-4d69-a9d1-ecbf61d25b6a.png)

**Comment by pcottle** [comment] 2022-10-10 20:33
This might be related to 01b11e1ac2774fc61c66dc6145f9404584f24363. Let me try reverting

**Comment by noahbowman** [comment] 2022-10-10 20:39
Yep, tested https://learngitbranching.js.org/?NODEMO on both Chome and Edge - works great! Also, checked Firefox again for good measure and that is still working OK.

**Comment by Holipori** [comment] 2022-10-11 04:20
> I just reverted this and I'm pushing the site now: [e11d691](https://github.com/pcottle/learnGitBranching/commit/e11d69148086411b4ab3e030512d569d0a262a1b)
> 
> can you try after a hard refresh (clearing cache) on https://learngitbranching.js.org/?NODEMO ?

Hi, I'm using Safari and Chrome on Mac. I just cleared my cache and tried https://learngitbranching.js.org/?NODEMO. It works on both browsers. But the tutorial sections still don't allow me to enter anything.

**Comment by dori-b9e** [comment] 2022-10-11 06:09
Pressing `tab` key multiple times will get your cursor back(Chrome, macOS).
Maybe some hidden input element is holding the cursor?

**Comment by Holipori** [comment] 2022-10-11 06:25
wow! It works. Thank you!

**Comment by waldyrious** [comment] 2022-10-11 07:52
CC @ulyssear for awareness :point_up:

**Comment by ulyssear** [comment] 2022-10-11 10:19
I may have found a solution and indeed, I put a code in the wrong place, which led to unintended consequences.

The code aiming to add the "inert" attribute was done via the "show" and "hide" methods present in the ModalView object, in the src\js\views\index.js file.
By moving it in the "toggleShow" method, near "stealKeyboard" and "releaseKeyboard", there is no longer any blocking on the console input. I'm going to do a PR that should solve this problem.

Anyway, sorry for that !

**Comment by imarman** [comment] 2022-10-11 14:04
> Pressing `tab` key multiple times will get your cursor back(Chrome, macOS). Maybe some hidden input element is holding the cursor?

It works, Thanks!

**Comment by pcottle** [comment] 2022-10-11 14:33
Just confirmed that the cursor no longer gets stolen for tutorials, so going to close this out

**Closed by pcottle** 2022-10-11 14:33 UTC

**Comment by dr1ver1** [comment] 2022-12-08 15:28
I have this issue. I've just used the site for the first time on a new computer. Windows 11 using Chrome. Pressing Tab multiple times seemed to fix it
