### ISSUE TITLE
i want to close "hide goal", i can not see anything, bu i can not close it using cmd

### ISSUE THREAD

**Issue by disxo** [pcottle/learnGitBranching#691] opened 2020-04-24 04:42 UTC
![image](https://user-images.githubusercontent.com/20137434/80175705-f080ad00-8628-11ea-9d71-731fb31fec8a.png)

**Comment by wasedawesley** [comment] 2020-04-24 06:27
same problem, maybe the server is shut down

**Comment by disxo** [comment] 2020-04-24 06:53
> same problem, maybe the server is shut down

yes, thank you , because i want to use it to make some practice.

**Comment by Inkognitoo** [comment] 2020-04-24 08:03
Issue and fix are already exist
Now we are waiting for approve pull request
https://github.com/pcottle/learnGitBranching/issues/688

**Comment by zhahuya** [comment] 2020-04-24 12:46
一个非常糟糕的错误！

**Comment by Blot1** [comment] 2020-04-24 14:22
same problem,what's wrong?

**Comment by gregzanch** [comment] 2020-04-24 23:33
still getting the same issue

**Comment by LebronAl** [comment] 2020-04-25 02:24
I was going to learn this last night, but when I opened it, I found this problem. It really affects the user experience.

**Comment by Ssicayoon** [comment] 2020-04-25 03:23
Same issue, hope it will be fixed soon

**Comment by zhangzzxiaohong** [comment] 2020-04-25 07:11
It make me sad.Hope it will be fixed as soon as qucikly

**Comment by hong4rc** [comment] 2020-04-25 09:00
> > same problem, maybe the server is shut down
> 
> yes, thank you , because i want to use it to make some practice.

You can try: hong4rc.github.io/test/index.html

**Comment by sriramdintakurti** [comment] 2020-04-25 09:04
> > > same problem, maybe the server is shut down
> > 
> > 
> > yes, thank you , because i want to use it to make some practice.
> 
> You can try: https://hong4rc.github.io/test/index.html

Thanks the new link is working

**Comment by tilakapash** [comment] 2020-04-25 13:28
Same problem. Breaks the whole funcionality of the app. Great app ... but useless unless this bug is corrected

**Comment by elodg** [comment] 2020-04-25 14:04
Duplicate of #688

**Comment by zawawimanja** [comment] 2020-04-25 16:53
same. hide goal not work.

**Comment by pcottle** [comment] 2020-04-25 18:54
Apologies everyone! #690 should fix this. Pushing an update now

**Comment by pcottle** [comment] 2020-04-25 18:55
Commit 9706b36d4edb5a0e9e424304023184d9360d36e4 just landed in prod, should be pushed out shortly and you can all try again then.

**Comment by pcottle** [comment] 2020-04-25 18:55
<img width="1269" alt="Screen Shot 2020-04-25 at 11 55 39 AM" src="https://user-images.githubusercontent.com/1135007/80288254-b1676000-86eb-11ea-9f2b-aed7b700100e.png">
Alright seems restored in prod 😅

**Comment by hong4rc** [comment] 2020-04-27 10:19
@disxo Can you close this issue?

**Closed** 2020-04-28 02:42 UTC
