### ISSUE TITLE
[BUG] Animation Not working on 7th level

### ISSUE THREAD

**Issue by Tinithrari** [pcottle/learnGitBranching#401] opened 2017-01-09 13:49 UTC
On the 7th level of the first category in Git remotes, the animation is not running and sometimes, it blocks the script on the website

Browser: firefox

**Comment by pcottle** [comment] 2017-01-10 00:09
Can you attach some screenshots or repro steps? To be honest we mainly just support Chrome :(

**Comment by ser-dev** [comment] 2017-02-11 23:02
Issue appears by just getting into that level, finishing it and not seeing the animation. I reproduced it on Firefox (requires using the arrows to be able to navigate to the Remote levels :) )

I couldn't make sure if this is the root cause, but just after pressing in the level number I get the following error in the console when loading this level with Firefox:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.  bundle.min.a9760fa4.js:2:5569
console.trace():  bundle.min.a9760fa4.js:2
	[3]</d.prototype.addListener http://localhost:63342/learnGitBranching/build/bundle.min.a9760fa4.js:2:5772
	d http://localhost:63342/learnGitBranching/build/bundle.min.a9760fa4.js:17:22985
	[243]</</l<.paperInitialize http://localhost:63342/learnGitBranching/build/bundle.min.a9760fa4.js:18:29143
	[243]</</l<.initialize/</< http://localhost:63342/learnGitBranching/build/bundle.min.a9760fa4.js:18:28856
	[11]</j.prototype.run http://localhost:63342/learnGitBranching/build/bundle.min.a9760fa4.js:2:26601
	i http://localhost:63342/learnGitBranching/build/bundle.min.a9760fa4.js:2:26109
```

Not sure if this causes the later lack of animation at the end, but I did not see this error in the other levels.

**Comment by pcottle** [comment] 2017-02-13 01:09
Thats quite odd, seems like there are a number of threads about this (with the exact 11 number too)
http://stackoverflow.com/questions/8313628/node-js-request-how-to-emitter-setmaxlisteners
http://stackoverflow.com/questions/9768444/possible-eventemitter-memory-leak-detected
https://github.com/npm/npm/issues/13806

can you try setting the max listeners to 100, and if that doesnt work, maybe 0 (unlimited)? 10 seems like such a small number

**Comment by ser-dev** [comment] 2017-02-13 20:49
Setting it to 100 made it work indeed, but there seems to be a leak of events of type=refreshTree.
Just by opening the level, 12 events are added to the array.

The following is printed by adding this in learnGitBranching\node_modules\events\events.js#140: 
```
    console.log('type=' + type + ', event array size=' + this._events[type].length);
    for (var i = 0; i < this._events[type].length; i++) {
      console.log(i+') event=' + this._events[type][i]);
    }
```

```
type=refreshTree, event array size=12  bundle.js:3301:5
0) event=function (speed) {

  if (!this.gitReady || !this.gitEngine.rootCommit) {

    return;

  }



  // this method can only be called after graphics are rendered

  this.fullCalc();



  this.animateAll(speed);

}  bundle.js:3303:7
1) event=function (speed) {

  if (!this.gitReady || !this.gitEngine.rootCommit) {

    return;

  }



  // this method can only be called after graphics are rendered

  this.fullCalc();



  this.animateAll(speed);

}  bundle.js:3303:7
2) 
```

and same until the 12th.
Then, when closing the instructions a total of 19 events appear in the _events array of type=refreshTree.
During the level, it is also possible to keep adding elements by typing: git clone, reset, git clone... but not sure if it is required to keep track even if 'reset' has been called :)

Would you know why so many events of type=refreshTree with the above function are being added?

**Comment by pcottle** [comment] 2017-02-17 00:34
yeah we register the event in the `GitVisuals` constructor, and we construct multiple objects pretty often. each cloned repo is actually to different trees, and each level is another tree (and the sandbox is another).

i dont think we are unregistering the events though, so let me try that

**Closed** 2017-02-17 00:45 UTC
