### ISSUE TITLE
Level intro3: "git checkout" without effect

### ISSUE THREAD

**Issue by Biganon** [pcottle/learnGitBranching#534] opened 2019-01-21 13:05 UTC
In the level intro3, the following steps work : 

git branch bugFix
git checkout bugFix
git commit

But at this point, issuing "git checkout" or "git checkout master" in order to go back to the master branch does not work as intended. A pair of arrows on a green background appears next to the command, and seems to imply that I should wait, yet nothing happens. The following commands are stuck with an empty square on a yellow background (except if I type an invalid command, in which case I get an exclamation mark on a red background).

I've tried on Firefox on Linux, Chromium on Linux, and Firefox on Windows, to no avail.

Using "git checkout master" works. But "git checkout" should work as well, and besides, after using it, all commands after it are without effect (as indicated above).

**Comment by grocky** [comment] 2019-03-01 23:50
Hi @Biganon, I'm not understanding what you were expecting for `git checkout`. Per the man pages

```man
 You could omit <branch>, in which case the command degenerates to "check out the current branch", which is a
           glorified no-op with rather expensive side-effects to show only the tracking information, if exists, for the current
           branch.
```

This is what I see when following the steps you describe:

![image](https://user-images.githubusercontent.com/1675518/53672885-80f47500-3c52-11e9-9bb6-7c7c5ff8428d.png)

The other behavior you describe does sound weird. I wasn't able to reproduce it though. I see a few prod releases in the git history, so maybe it was fixed indirectly already?

**Comment by pcottle** [comment] 2019-03-06 23:56
Whoops sorry I missed this, but:

>  pair of arrows on a green background appears next to the command, and seems to imply that I should wait, yet nothing happens. The following commands are stuck with an empty square on a yellow background 

this usually means something failed in the JS execution and the app is essentially broken/in an invalid state from there on out. did you end up resolving this? it might be due to using firefox

**Closed** 2019-03-06 23:56 UTC
