### ISSUE TITLE
layout is broken in Google Chrome browser.

### ISSUE THREAD

**Issue by szkaym** [pcottle/learnGitBranching#706] opened 2020-05-11 05:07 UTC
this app is great useful to git learning.
but layout is broken in the Google Chrome.
if same "Issues" is exist, please close this.

thanks.

![スクリーンショット 2020-05-11 13 57 59](https://user-images.githubusercontent.com/1326428/81525744-a91c4f80-9390-11ea-8cac-85a195920afa.png)

**Comment by pcottle** [comment] 2020-05-11 16:04
<img width="1285" alt="Screen Shot 2020-05-11 at 9 03 11 AM" src="https://user-images.githubusercontent.com/1135007/81583438-3f874b80-9366-11ea-9654-c9c304a62c2c.png">
Can you specify your chrome version and platform? it works fine for me on Chrome 81.0.4044.138 and Mojave 10.14.6

**Comment by szkaym** [comment] 2020-05-11 23:48
My Chrome version is 81.0.4044.138（Official Build） on macOS Catalina (10.15.4).
Browser Extension is nothing.

**Comment by pcottle** [comment] 2020-05-12 02:38
Wow! maybe this is a catalina bug? its an 8gb update but ill try to update tmr or tonight so I can test myself...

**Comment by szkaym** [comment] 2020-05-12 03:09
Oh... Thank you.

In the Safari looks like is OK.
![スクリーンショット 2020-05-12 12 08 30](https://user-images.githubusercontent.com/1326428/81634167-59e62580-9449-11ea-9c6d-a413f1530084.png)

**Comment by nem75** [comment] 2020-05-12 07:48
I cannot reproduce this, works fine for me.

macOS 10.15.4 (19E287)
Chrome Version 81.0.4044.138 (Official Build) (64-bit)
No extensions

**Comment by szkaym** [comment] 2020-05-12 08:19
I apologize to owner.

My display URL was not your repo.
my report wabpage was others builded by use old version.
I come from "Fork me on Github" link and wrote this Issue.
that webpage is ( http://k.swd.cc/learnGitBranching-ja/ ).

thank you nem75, I can apologize to owner.
I report  this Issue to k.swd.cc.

**Comment by pcottle** [comment] 2020-05-12 16:59
Thanks for the clarification and thanks for checking @nem75  :) going to close this out since our repo is fine

**Closed by pcottle** 2020-05-12 16:59 UTC
